import test from 'node:test';import assert from 'node:assert/strict';import {handleApi as api} from '../src/http.js';
const handleApi=(request,storage)=>api(request,storage,{ownerEmail:'owner@example.com'});import {extractReceipt} from '../src/receipt.js';
function memory(){let record=null;const files=new Map();return {read:async()=>structuredClone(record),init:async state=>{record??={state:structuredClone(state),revision:0};},save:async(state,revision)=>{if(record.revision!==revision)throw Error('Save conflict');record={state:structuredClone(state),revision:revision+1};},putFile:async(key,file)=>files.set(key,{body:await file.arrayBuffer(),type:file.type}),getFile:async key=>files.get(key)}}
const request=(path,email,body)=>new Request('https://renovation.test'+path,{method:body?'POST':'GET',headers:{...(email?{'oai-authenticated-user-email':email,'oai-authenticated-user-id':email}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
test('authentication, invitation acceptance, assigned-task write and contractor isolation',async()=>{const s=memory();assert.equal((await handleApi(request('/api/state'),s)).status,401);const owner=await (await handleApi(request('/api/state','owner@example.com'),s)).json();assert.equal(owner.user.role,'Owner');assert.equal((await handleApi(request('/api/state','stranger@example.com'),s)).status,403);assert.equal((await handleApi(request('/api/action','owner@example.com',{type:'invite.create',email:'builder@example.com',name:'Builder',role:'Contractor',contractorId:'c1'}),s)).status,200);const builder=await (await handleApi(request('/api/state','builder@example.com'),s)).json();assert.equal(builder.user.contractorId,'c1');assert.equal(builder.state.expenses,undefined);assert.ok(builder.state.tasks.every(t=>t.contractorId==='c1'));assert.equal((await handleApi(request('/api/action','builder@example.com',{type:'task.move',id:'t8',status:'Blocked'}),s)).status,200);assert.equal((await handleApi(request('/api/action','builder@example.com',{type:'task.move',id:'t3',status:'Done'}),s)).status,403);assert.equal((await handleApi(request('/api/action','builder@example.com',{type:'expense.approve',id:'e7'}),s)).status,403);assert.equal((await handleApi(request('/api/state?demo=partner','builder@example.com'),s)).status,403);});
test('receipt extraction, uploaded bytes, confirmation and draft removal',async()=>{const parsed=extractReceipt('HOME SUPPLY\n2026-10-08\nSubtotal 120.00\nTax 10.50\nTOTAL $130.50');assert.equal(parsed.vendor,'HOME SUPPLY');assert.equal(parsed.date,'2026-10-08');assert.equal(parsed.amount,130.5);const s=memory();await handleApi(request('/api/state','owner@example.com'),s);const form=new FormData();form.append('file',new File([new Uint8Array([1,2,3])],'receipt.png',{type:'image/png'}));form.append('ocrText','HOME SUPPLY\n2026-10-08\nTOTAL $130.50');const response=await handleApi(new Request('https://renovation.test/api/receipts',{method:'POST',headers:{'oai-authenticated-user-email':'owner@example.com'},body:form}),s);const data=await response.json();assert.equal(response.status,200);assert.equal(data.draft.amount,130.5);const file=await handleApi(request(data.draft.receiptUrl,'owner@example.com'),s);assert.equal(file.headers.get('content-type'),'image/png');assert.equal((await file.arrayBuffer()).byteLength,3);const confirmed=await (await handleApi(request('/api/action','owner@example.com',{type:'expense.add',expense:{vendor:data.draft.vendor,date:data.draft.date,amount:data.draft.amount,roomId:'kitchen',category:'materials',receiptDraftId:data.draft.id}}),s)).json();assert.equal(confirmed.state.receiptDrafts.length,0);assert.equal(confirmed.state.expenses.at(-1).receiptUrl,data.draft.receiptUrl);});

test('configured owner recovers a misinitialized owner without losing renovation data',async()=>{const s=memory();const initial=await api(request('/api/state','preview@example.com'),s,{local:true});assert.equal(initial.status,200);const recovered=await handleApi(request('/api/state','owner@example.com'),s);assert.equal(recovered.status,200);const data=await recovered.json();assert.equal(data.user.role,'Owner');assert.equal(data.user.email,'owner@example.com');assert.equal(data.state.tasks.length,11);assert.equal((await handleApi(request('/api/state','preview@example.com'),s)).status,403);});
test('only configured owner can initialize a hosted project',async()=>{const s=memory();assert.equal((await handleApi(request('/api/state','preview@example.com'),s)).status,403);assert.equal(await s.read(),null);assert.equal((await handleApi(request('/api/state','owner@example.com'),s)).status,200);});
